# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e6c6036f466be48f9cda092faa0ddbb0ed1935ae5f630aefdc420e30d4d7b8bf4649e4227abb86d203697f5c5c7108f7f139ca80ffb64627afba08b56af2c37

test:
  secret_key_base: d5148cf01f5c1494617e893735bbb6947f941884026965a56ab419e4cb07a9562ab00efc2a29affdc280ea89df7933e49f1e9ca2c1949bc7d28fad5d63a36ecd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
